# After changing this file, check it on:
#   http://lint.travis-ci.org/


language: c
#python:
#    - 3.3
#    - 3.4

install:
    - cd /home/travis/build
    - git clone --depth=50 --branch=master git://github.com/gramps-project/gramps.git gramps-project/gramps
    - cd gramps-project/gramps
    - time sudo apt-get update
    - travis_retry sudo apt-get install gir1.2-pango gir1.2-gtk xdg-utils librsvg2-common libglib2.0-dev intltool 
    - travis_retry sudo apt-get install python3-gobject python3-gi python3-cairo python3-gi-cairo python3-bsddb3 python3-dev python3-nose
    - travis_retry sudo apt-get install xvfb libgtk-3-dev

    - travis_retry curl https://bootstrap.pypa.io/get-pip.py | sudo python3
    - travis_retry sudo pip3 install Django==1.7
    - travis_retry sudo pip3 install pyicu==1.8
    - travis_retry sudo pip3 install mock
    - python3 setup.py build

    - cd ..
    - git clone --depth=50 --branch=master git://github.com/gramps-project/addons-source.git addons-source
    - cd addons-source
    - python3 -m compileall *

before_script:
    - export DISPLAY=:0
    - sudo Xvfb :0 -ac -screen 0 1024x768x24 &

script:
    -  mkdir -p /home/travis/.gramps/grampsdb/
    -  mkdir -p /home/travis/.gramps/gramps50/
    -  ln -s /home/travis/build/gramps-project/addons-source /home/travis/.gramps/gramps50/plugins
    -  GRAMPS_RESOURCES=../gramps PYTHONPATH=../gramps nosetests3 -vv
